CREATE TABLE IF NOT EXISTS customer_cohort (
    user_id BIGINT PRIMARY KEY,
    age INTEGER NOT NULL,
    has_children BOOLEAN NOT NULL,
    is_married BOOLEAN NOT NULL,
    cnt_trips REAL,
    avg_diff_trip_days REAL,
    days_last_trip INTEGER,
    avg_days_advance_booking REAL,
    avg_travel_days REAL,
    avg_seats REAL,
    avg_checked_bags REAL,
    avg_flight_travel_days REAL,
    avg_distance_km REAL,
    avg_rooms REAL,
    avg_hotel_nights REAL,
    min_signup_date TIMESTAMP,
    avg_session_duration_seconds REAL,
    flight_booked INTEGER,
    hotel_booked INTEGER,
    avg_flight_discount REAL,
    avg_hotel_discount REAL,
    month_active REAL,
    sessions_per_month REAL,
    trips_per_month REAL,
    page_click_per_session REAL,
    trips_per_session REAL,
    avg_booking_value REAL,
    customer_value_per_month REAL,
    flight_booking_value REAL,
    hotel_booking_value REAL,
    cancellation_rate REAL,
    total_discount_rate REAL,
    discount_per_km REAL,
    flight_discount_rate REAL,
    hotel_discount_rate REAL
);